---
-
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  vars:
  tasks:
  - name: Count our fruit
    ansible.builtin.debug:
      msg: "{{ item }} with index {{ my_idx }}"
    loop:
      - apple
      - banana
      - pear
    loop_control:
      index_var: my_idx
...
