---
-
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  vars:
    tag_data:
      Environment: dev
      Application: payment
  tasks:
    - name: Using dict2items
      debug:
        msg: "{{ item.key }} - {{ item.value }}"
      loop: "{{ tag_data | dict2items }}"  
...